@echo off
set str=%1
set str=%str:a=A% 
set str=%str:b=B% 
set str=%str:c=C% 
set str=%str:d=D% 
set str=%str:e=E% 
set str=%str:f=F% 
set str=%str:g=G% 
set str=%str:h=H% 
set str=%str:i=I% 
set str=%str:j=J% 
set str=%str:k=K% 
set str=%str:l=L% 
set str=%str:m=M% 
set str=%str:n=N% 
set str=%str:o=O% 
set str=%str:p=P% 
set str=%str:q=Q% 
set str=%str:r=R% 
set str=%str:s=S% 
set str=%str:t=T% 
set str=%str:u=U% 
set str=%str:v=V% 
set str=%str:w=W% 
set str=%str:x=X% 
set str=%str:y=Y% 
set str=%str:z=Z% 
echo %str%